ARG FROM_IMAGE
ARG JOBS_IN_PARALLEL

FROM $FROM_IMAGE as build
LABEL maintainer="yaroslav429@gmail.com"

ENV container docker
ENV HOME /root

RUN zypper -n install php7 php7-ctype php7-json && \
    zypper clean

RUN zypper -n install git which gcc gcc-c++ zlib gperf openssl libopenssl-devel cmake php7-devel php7-embed && \
    zypper clean

COPY . $HOME/phptdlib

RUN cd $HOME && \
    git clone https://github.com/CopernicaMarketingSoftware/PHP-CPP.git && \
    cd $HOME/PHP-CPP && \
    make -j $JOBS_IN_PARALLEL && \
    make install && \
    make clean

RUN cd $HOME/phptdlib && mkdir build && cd build && \
    cmake -DTDLIB_BUILD_TESTS=ON .. && \
    cmake --build . -- -j $JOBS_IN_PARALLEL && \
    sudo cmake --build . --target install

RUN $HOME/phptdlib/build/tester




FROM $FROM_IMAGE
LABEL maintainer="yaroslav429@gmail.com"
ENV container docker
ENV HOME /root

RUN zypper -n install php7 php7-ctype php7-json && \
    zypper clean

COPY --from=build /usr/lib/libphpcpp.so* /usr/lib/
COPY --from=build /usr/lib64/php7/extensions/tdlib.so /usr/lib64/php7/extensions/
COPY --from=build /etc/php7/conf.d/tdlib.ini /etc/php7/conf.d/

RUN /sbin/ldconfig

ENTRYPOINT ["php"]
